Repository surfstudio/flutter-swipe-refresh, pull requests merged in 2024-03, with the labels that each got.

#31 chore(SNP-903): Fix and update CI, add new templates, update FVM
  .fvm/fvm_config.json
  .fvmrc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_update.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/documentation_update.md
  .github/PULL_REQUEST_TEMPLATE/new_feature.md
  .github/workflows/main.yml
  .github/workflows/new_issue_to_pyrus_task.yml
  .github/workflows/new_issues_label.yml
  .github/workflows/new_pull_request_label.yml
  .github/workflows/new_pull_request_main_actions.yml
  .github/workflows/publish_to_pub.yml
  .gitignore
Labels: new pull request

#32 feat: Supporting new os
  .fvmrc
  CHANGELOG.md
  dart_dependency_validator.yaml
  example/.fvm/fvm_config.json
  example/ios/Flutter/AppFrameworkInfo.plist
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  example/ios/Runner/Info.plist
  example/lib/main.dart
  example/lib/screens/main_page.dart
  example/lib/screens/my_app.dart
  example/pubspec.yaml
  lib/src/cupertino_swipe_refresh.dart
  lib/src/material_swipe_refresh.dart
  lib/src/swipe_refresh.dart
  lib/src/swipe_refresh_base.dart
  lib/src/widgets/conditional_wrapper.dart
  lib/src/widgets/scroll_behavior_in_web.dart
  lib/utills/platform_wrapper.dart
  pubspec.yaml
  test/platform_wrapper_test.dart
  test/swipe_refresh_adaptive_test.dart
  test/swipe_refresh_builder_test.dart
  test/swipe_refresh_cupertino_test.dart
  test/swipe_refresh_material_test.dart
Labels: bug, enhancement

#2 feat: Add cache extent property
  CHANGELOG.md
  example/pubspec.lock
  lib/src/cupertino_swipe_refresh.dart
  lib/src/material_swipe_refresh.dart
  lib/src/swipe_refresh.dart
  pubspec.lock
Labels: enhancement

#26 fix: Updates build badge route.
  README.md
Labels: bug, new pull request

#33 chore: Prepare release
  .markdownlint.json
  CHANGELOG.md
  README.md
  lib/src/material_swipe_refresh.dart
  pubspec.yaml
Labels: enhancement, Release preparation
